In [8]:
import pandas as pd
data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [5]:
X = pd.DataFrame(data, columns=["age","studytime","famrel","freetime","goout"])
X.head()

age  studytime  famrel  freetime  goout
0   18          2       4         3      4
1   17          2       5         3      3
2   15          2       4         3      2
3   15          3       3         2      2
4   16          2       4         3      2

In [6]:
y = pd.DataFrame(data, columns=["sex"])
y.head()

sex
0   F
1   F
2   F
3   F
4   F

In [9]:
import numpy as np
X1=np.array(X)
y1=np.array(y)
print(X1)
print(y1)

[[18  2  4  3  4]
 [17  2  5  3  3]
 [15  2  4  3  2]
 ...
 [21  1  5  5  3]
 [18  1  4  4  1]
 [19  1  3  2  3]]
[['F']
 ['F']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['F']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['M']
 ['F']
 ['M']
 ['F

In [10]:
from sklearn import tree
clasificador = tree.DecisionTreeClassifier()
clasificacion = clasificador.fit(X,y)
print(clasificacion)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [12]:
prediccion=clasificacion.predict([[16,2,3,2,2]])
print(prediccion)

['M']
