Seleccionamos el Dataset "Consumo de Alcohol por parte de los Estudiantes"

In [1]:
import pandas as pd
data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

Creamos un dataframe con datos numericos para preprocesarlos

In [10]:
df1 = pd.DataFrame(data, columns=["age","studytime","famrel","freetime","goout"])
df1.head()

age  studytime  famrel  freetime  goout
0   18          2       4         3      4
1   17          2       5         3      3
2   15          2       4         3      2
3   15          3       3         2      2
4   16          2       4         3      2

Convertimos en array el dateframe

In [11]:
import numpy as np
matriz = np.array(df1)
print(matriz)

[[18  2  4  3  4]
 [17  2  5  3  3]
 [15  2  4  3  2]
 ...
 [21  1  5  5  3]
 [18  1  4  4  1]
 [19  1  3  2  3]]


Utilizamos la libreria sklearn para el preprocesamiento

In [6]:
from sklearn import preprocessing

Preprocesamiento Escala

In [15]:
matriz_salida_escala = preprocessing.scale(matriz)
print(matriz_salida_escala)

[[ 1.02304645 -0.04228585  0.06219406 -0.2360102   0.8014793 ]
 [ 0.23837976 -0.04228585  1.17886012 -0.2360102  -0.09790798]
 [-1.33095364 -0.04228585  0.06219406 -0.2360102  -0.99729526]
 ...
 [ 3.37704655 -1.23535078  1.17886012  1.76880766 -0.09790798]
 [ 1.02304645 -1.23535078  0.06219406  0.76639873 -1.89668255]
 [ 1.80771315 -1.23535078 -1.054472   -1.23841914 -0.09790798]]


C:\Users\Ronald\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


Preprocesamiento Normalizado

In [17]:
matriz_salida_normalize = preprocessing.normalize(matriz)
print(matriz_salida_normalize)

[[0.93704257 0.10411584 0.20823168 0.15617376 0.20823168]
 [0.92742603 0.10910895 0.27277236 0.16366342 0.16366342]
 [0.93385921 0.12451456 0.24902912 0.18677184 0.12451456]
 ...
 [0.93821081 0.04467671 0.22338353 0.22338353 0.13403012]
 [0.95132956 0.05285164 0.21140657 0.21140657 0.05285164]
 [0.96958969 0.05103104 0.15309311 0.10206207 0.15309311]]


Preprocesamiento Discretizacion

In [20]:
matriz_salida_Discretizer = preprocessing.KBinsDiscretizer(matriz)
print(matriz_salida_Discretizer)

KBinsDiscretizer(encode='onehot',
         n_bins=array([[18,  2, ...,  3,  4],
       [17,  2, ...,  3,  3],
       ...,
       [18,  1, ...,  4,  1],
       [19,  1, ...,  2,  3]], dtype=int64),
         strategy='quantile')
